name: Run Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [">=3.13"]
    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test with python ${{ matrix.python-version }}
        run: uv run -m pytest

    # steps:
    #   - uses: actions/checkout@v5
    #   - uses: astral-sh/setup-uv@v5
    #   - name: Set up Python
    #     uses: actions/setup-python@v5
    #     with:
    #       python-version: '>3.13.0'

    #   - name: Display Python version
    #     run: python -c "import sys; print(sys.version)"

    #   - name: Install dependencies
    #     run: |
    #       uv install

    #   - name: Run tests
    #     run: |
    #       uv run -m test

