name: Run checks and types with ruff and mypy

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv + Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"

      - name: Ruff lint
        run: uv run ruff check . --output-format=github

      - name: Ruff format check
        run: uv run ruff format . --check --diff

      - name: MyPy type check
        run: uv run mypy .